### ISSUE TITLE
Depend on XML cookbook

### ISSUE THREAD

**Issue by slyness** [hw-cookbooks/route53#62]
Depend on XML cookbook to include dependencies that were previously not always met for nokogiri gem installation.

**Comment by cwjohnston** [comment]
This should reduce complexity on our end by removing code, i.e. [these lines](https://github.com/hw-cookbooks/route53/blob/develop/recipes/default.rb#L20-L43) could all be replaced with `include_recipe 'xml'

**Comment by agoddard** [comment]
added in 0.4.0
